version: '3.9'

services:

  api:
    build:
      context: .
      dockerfile: IntelliBudgetApi/Dockerfile
    container_name: intellibudget-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=intellibudget;User=root;Password=123456;

  mysql:
    image: mysql:8.0
    container_name: intellibudget-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: intellibudget
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: